apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaui.image }}"
          ports:
            - containerPort: {{ .Values.kafkaui.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "Meu-Cluster-K8s"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ .Release.Name }}-kafka:{{ .Values.kafka.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-ui
spec:
  ports:
    - port: {{ .Values.kafkaui.port }}
      targetPort: {{ .Values.kafkaui.port }}
  selector:
    app: {{ .Release.Name }}-kafka-ui
